export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const RETURN_SIGNUP = 'RETURN_SIGNUP';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const EMAIL_VERIFICATION ="EMAIL_VERIFICATION";
export const RETURN_LOGIN="RETURN_LOGIN";

export const LOAD_TOPIC_START = "LOAD_TOPIC_START";
export const LOAD_TOPIC_SUCCESS = "LOAD_TOPIC_SUCCESS"
export const LOAD_TOPIC_FAIL = "LOAD_TOPIC_FAIL";
export const LOAD_CURRENT_NOTE_START = "LOAD_CURRENT_NOTE_START"
export const LOAD_CURRENT_NOTE_SUCCESS = "LOAD_CURRENT_NOTE_SUCCESS"
export const LOAD_CURRENT_NOTE_FAIL = "LOAD_CURRENT_NOTE_FAIL"